### ISSUE TITLE
Hi is this project still alive?

### ISSUE THREAD

**Issue by mingrui** [joaofcosta/shizzles#14]
Hi!

Is the project still alive?
In the presentation I see there is a large dataset, I'm wondering if you can share the dataset?
I am working on a similar problem.

Thanks!

**Comment by dinocosta** [comment]
@mingrui Sorry for the really late delay. This project is not currently maintained as it was used only for a university assignment.
Anyway we could not share the dataset because we were working with confidential data.

Good luck and thank you for your interest 👍
